name: Cloudtype Monitor

on:
  schedule:
    # 05:01 ~ 05:11 KST (UTC+9 → UTC 20:01 ~ 20:11), 매일 2분 간격
    - cron: "1,3,5 20 * * *"
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    env:
      CLOUDTYPE_ID: ${{ secrets.CLOUDTYPE_ID }}
      CLOUDTYPE_PW: ${{ secrets.CLOUDTYPE_PW }}
      EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build and run Selenium script in Docker
        run: |
          docker build -t cloudtype-monitor .
          docker run \
            -e CLOUDTYPE_ID="${{ secrets.CLOUDTYPE_ID }}" \
            -e CLOUDTYPE_PW="${{ secrets.CLOUDTYPE_PW }}" \
            -e EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }} \
            -e EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }} \
            cloudtype-monitor
