name: Restart Cloudtype (Docker)

on:
  schedule:
    - cron: '1,3,5 20 * * *'
  workflow_dispatch:

jobs:
  run-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Dockerized Selenium script
        env:
          CLOUDTYPE_ID: ${{ secrets.CLOUDTYPE_ID }}
          CLOUDTYPE_PW: ${{ secrets.CLOUDTYPE_PW }}
        run: |
          docker build -t cloudtype-restart .
          docker run -e CLOUDTYPE_ID -e CLOUDTYPE_PW cloudtype-restart
