name: Auto Restart Cloudtype Service

on:
  schedule:
    # 한국 시간 05:01~05:11 → UTC 기준 20:01~20:11 (전날 오후 8시 1분~11분)
    - cron: '1,3,5 20 * * *'
  workflow_dispatch:

jobs:
  restart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Chrome & ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip xvfb
          
          # Install Chrome
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          
          # Get Chrome version
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
          
          # Download matching ChromeDriver version
          DRIVER_VERSION=$(wget -qO- https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
          wget -O chromedriver.zip https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver.zip
          sudo mv chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium python-dotenv

      - name: Create .env file
        run: |
          echo "CLOUDTYPE_ID=${{ secrets.CLOUDTYPE_ID }}" >> .env
          echo "CLOUDTYPE_PW=${{ secrets.CLOUDTYPE_PW }}" >> .env

      - name: Run Selenium Script
        run: |
          xvfb-run python your_script.py
